# Generated by Django 4.0.1 on 2022-01-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_person_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Phone',
            new_name='phone',
        ),
    ]
