# Generated by Django 4.0.1 on 2022-01-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_city_province_person_married_person_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
