# Generated by Django 4.0.1 on 2022-01-27 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_person_birthday_alter_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.BooleanField(null=True, verbose_name='حنسیت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='natnionalcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='postalcode',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='shenasnamehcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
