# Generated by Django 4.0.1 on 2022-01-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_person_gender_alter_person_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
