# Generated by Django 4.0.1 on 2022-01-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_person_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mother',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
