# Generated by Django 4.0.1 on 2022-01-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_person_mother'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birthday',
            new_name='birth_day',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Married',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='brother',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='natnionalcode',
            new_name='natnional_code',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='shenasnamehcode',
            new_name='shenasnameh_code',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='phone',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='car',
        ),
        migrations.RemoveField(
            model_name='person',
            name='carno',
        ),
        migrations.RemoveField(
            model_name='person',
            name='child',
        ),
        migrations.RemoveField(
            model_name='person',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='person',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='motorcycle',
        ),
        migrations.RemoveField(
            model_name='person',
            name='motorcycleno',
        ),
        migrations.RemoveField(
            model_name='person',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='person',
            name='sister',
        ),
        migrations.AddField(
            model_name='person',
            name='married',
            field=models.BooleanField(null=True),
        ),
    ]
