# Generated by Django 4.0.1 on 2022-01-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_person_address_alter_person_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='provice_eng_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام انگلیسی'),
        ),
    ]
